version: '3.8'
services:
  app:
    image: mikhailkuzmich/search-engine-app
    container_name: search-engine
    ports:
      - "8080:8080"
    environment:
      APP_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/search_engine
      SPRING_APPLICATION_JSON: '{
      "externaldata": {
        "site-array": [
          {"url": "https://imkliva.by", "name": "страховая компания"},
          {"url": "https://www.svetlovka.ru", "name": "Библиотека"}
          ]
        }
      }'
    networks:
      - app-net
#    restart: always
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres_db
    networks:
      - app-net
#    restart: always
    environment:
      POSTGRES_DB: search_engine
      POSTGRES_USER: zero
      POSTGRES_PASSWORD: one
    ports:
      - "5432:5432"
    volumes:
      - /d/db-search-engine/:/var/lib/postgresql/data
networks:
  app-net:
    driver: bridge
#volumes:
#  db-volume: