version: '3'
services:
  psql:
    image: postgres:14
    container_name: server_psql
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_USER: zero
      POSTGRES_PASSWORD: one
      POSTGRES_DB: bookshop_db
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "kmv85@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "one"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
    - postgres

volumes:
  database-data:

networks:
  postgres:
    driver: bridge