spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/simpleshop
    username: zero
    password: one
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
springdoc:
  api-docs:
    enabled: true
