server:
  port: 8080
  contextPath: /admin

spring:
  datasource:
    username: zero
    password: one
    url: jdbc:postgresql://localhost:5432/search_engine
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changeset/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  thymeleaf:
    prefix: classpath:/templates/
  web:
    resources:
      static-locations: classpath:/static/
externaldata:
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36
  referrer: https://www.google.com
  site-array:
    #    - url: http://www.playback.ru
    #      name: Интернет-магазин
    #    - url: https://ipfran.ru
    #      name: ИПФ РАН
    #    - url: http://radiomv.ru
    #      name: радио
    #    - url: https://volochek.life
    #      name: Вышний Волочек
    #    - url: https://dombulgakova.ru
    #      name: Булгаковский дом
    - url: https://nikoartgallery.com
      name: Галерея Никогосяна
    #    - url: https://www.svetlovka.ru
    #      name: ЦГМБ им.М.А.Светлова
    #    - url: https://imkliva.by
    #      name: Страховая компания
    - url: https://et-cetera.ru/mobile/
      name: Театр
